# Generated by Django 2.2.16 on 2023-07-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='balance',
            field=models.FloatField(blank=True, verbose_name='баланс'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='count_unisender',
            field=models.IntegerField(blank=True, verbose_name='Счётчик запросов unisender'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='donat',
            field=models.FloatField(blank=True, verbose_name='Всего поступлений'),
        ),
    ]
