# Generated by Django 2.2.16 on 2023-07-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='date_balance',
            field=models.DateField(verbose_name='Дата проверки баланса'),
        ),
    ]
